name: Master Build

on: push

jobs:
  build-service:
    name: Master - Build MSP Service Container
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
    
    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v2.3.4
        run: npm test